# Generated by Django 5.2.1 on 2025-05-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFotografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
