# Generated by Django 5.2.1 on 2025-05-15 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportefotografico',
            name='fecha',
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='cliente',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='codigo_proyecto',
            field=models.CharField(default='Sin definir', max_length=50, verbose_name='Código del proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='contratista',
            field=models.CharField(default='Sin definir', max_length=200, verbose_name='Contratista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='elaborado_por',
            field=models.CharField(default='Sin definir', max_length=100, verbose_name='Elaborado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='inicio_supervision',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Inicio de la Supervisión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='mes_actual_obra',
            field=models.PositiveIntegerField(default=1, verbose_name='Mes Actual de Obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='reporte_numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Reporte N°'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='revisado_por',
            field=models.CharField(default='Sin definir', max_length=100, verbose_name='Revisado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportefotografico',
            name='version_reporte',
            field=models.CharField(default='01', max_length=10, verbose_name='Versión del reporte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportefotografico',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reportefotografico',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Fotografía 01'),
        ),
        migrations.AlterField(
            model_name='reportefotografico',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Fotografía 02'),
        ),
        migrations.AlterField(
            model_name='reportefotografico',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Fotografía 03'),
        ),
        migrations.AlterField(
            model_name='reportefotografico',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Fotografía 04'),
        ),
        migrations.AlterField(
            model_name='reportefotografico',
            name='proyecto',
            field=models.CharField(max_length=200, verbose_name='Proyecto'),
        ),
    ]
